### PR TITLE
Added Github Auth

### LINKED ISSUE #272: Firebase GitHub Authentication

### PR DESCRIPTION
**Pull request by rish07**
Fixes #272 
Let me know if there is something to be changed!

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@rish07 Can you hide the Client Id and Secret by replacing your id and secret with a blank or just text?

**Comment by rish07** [comment]
@himanshusharma89 sure

**Comment by rish07** [comment]
@himanshusharma89 I used the client ID and Secret of the firebase account project you added me in. I'll replace it with CLIENT_ID and CLIENT_SECRET and push again

**Comment by himanshusharma89** [comment]
BTW @rish07 Why are there so many lines of code?

**Comment by rish07** [comment]
@himanshusharma89 I think the .gitignore file did not contain .idea by default and I didn't change anything else except the auth.dart and in signUp screen. So it pushed the .idea system file changes as well.

**Comment by himanshusharma89** [comment]
Okay, no issues. Merging it.

**Pull request merged**
