### PR TITLE
Developed Login screen UI

### LINKED ISSUE #206: Login Page
**Describe the solution you'd like**
Make the Login screen as same as the _mockup_

**Contents**
1. Use Proper fonts 
2. Use already existing icons on the page.
3. For the UI elements refer to the website [www.flaticon.com](https://www.flaticon.com/).

**Please mention the work you are doing before I assign u this task.**
**Follow the UI Strictly**

Any files needed Just Contact me or other mentors

### PR DESCRIPTION
**Pull request by Rukmini-Meda**
Fixes #206 

Changes made:
- Login screen developed

Files changed, added or removed:
- lib/main.dart
- lib/app.dart
- lib/screens/ui/login.dart

Screenshots:

Screenshot (142)

Screenshot (143)

Screenshot (145)

### CODE REVIEW

**Comment by Rukmini-Meda** [comment]
I have developed the login screen UI as per the read me following the UI design strictly. Please review my PR and merge. Thank you.

**Comment by Rukmini-Meda** [comment]
Also, can you help me resolve the checks that were not successful. I have no idea about it.

**Comment by Rukmini-Meda** [comment]
@anushbhatia Please reply soon.

**Comment by anushbhatia** [comment]
Ok so basically if u wanna know why your checks failed just hover over the checks tab in this PR.
There are many reasons this happens it might be if u had not used the latest branch or there might be small indentation faults. This topic is too vast lol pm me on slack to know more

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Everything is great!!
Just reduce the size of all the widgets(Scale it little bit smaller)
Add action to sign up button in this.

**Comment by Rukmini-Meda** [comment]
I have made changes as you said. I have scaled it down and added a toggle function to signup button that redirects to sign up screen on clicking on it. Screenshots for the same are

Screenshot (147)


Screenshot (148)


Please review and merge. Thank you!

**Review by anushbhatia — APPROVED** [review]
Nice work done @Rukmini-Meda ;)

**Pull request merged**
