### PR TITLE
added intro screens

### PR DESCRIPTION
**Pull request by SirusCodes**
Intro screens added
Issue #270

### CODE REVIEW

**Comment by himanshusharma89** [comment]
Hey @SirusCodes, can you rebase your code because the GitHub auth in auth.dart is commented now.

**Comment by SirusCodes** [comment]
done @himanshusharma89

**Comment by himanshusharma89** [comment]
@SirusCodes Some of the files are already pushed, can you rebase it again?

**Comment by SirusCodes** [comment]
Is it having issues yet? @himanshusharma89

**Comment by himanshusharma89** [comment]
@SirusCodes Ignore the .github folder while committing and push it, those files are already updated. After that, we are good to go.

**Comment by SirusCodes** [comment]
I removed .github from git locally @himanshusharma89

**Comment by himanshusharma89** [comment]
@SirusCodes Not like deleting them all, just don't add them with `git add .` You can just use `git add lib/*`, commit them and push it.

**Comment by SirusCodes** [comment]
Done @himanshusharma89

**Comment by himanshusharma89** [comment]
@SirusCodes Still the files are missing. If you are facing issues, add everything commit it then pull the master branch. If you need more help, let me know.

**Comment by SirusCodes** [comment]
Which files are missing? Is it .github? @himanshusharma89

**Comment by himanshusharma89** [comment]
@SirusCodes The ISSUE_TEMPLATE in .github.

**Comment by SirusCodes** [comment]
Okk fixing it

**Comment by himanshusharma89** [comment]
@SirusCodes You can revert back to a particular commit and then work on it.

**Comment by SirusCodes** [comment]
@himanshusharma89 done

**Comment by himanshusharma89** [comment]
@SirusCodes Read this carefully, you need to add only the files that you worked upon, I saw a few files in this PR that are already present in the code. So don't do `git add .` instead of this use `git add lib/ file_name`

**Comment by SirusCodes** [comment]
> @SirusCodes Read this carefully, you need to add only the files that you worked upon, I saw a few files in this PR that are already present in the code. So don't do `git add .` instead of this use `git add lib/ file_name`

I'm not doing any `git add .` command those extra files are either image or some formatting changes which were made by my IDE. They won't cause any issues to the project!!

**Comment by himanshusharma89** [comment]
@SirusCodes It is perfect now, merging it.

**Pull request merged**
