### PR TITLE
Updated ReadMe,Removed repeated imports and the related bugs

### LINKED ISSUE #35: Remove repeated imports and related bugs

### PR DESCRIPTION
**Pull request by Anushka-shukla**
Updated the ReadMe file for the description of the application, removed some repeated imports and solved some error in home.dart file.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
We'll review it shortly..Meanwhile I am creating an issue..Just comment in it so that I can assign it to for grading

**Comment by Anushka-shukla** [comment]
> We'll review it shortly..Meanwhile I am creating an issue..Just comment in it so that I can assign it to for grading

Okay sir.

**Comment by smaranjitghose** [comment]
I have created the issue...Please claim it

**Review by swat1998 — APPROVED** [review]
changes for basic path changes

**Comment by swat1998** [comment]
Approved

**Pull request closed without merging**
