### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by himanshusharma89**
@ousnik @sukkritsharmaofficial 
Added a **badge** and connected the License.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
I have fixed some minor bugs in home page #20 
Performed AndroidX integration

**Comment by himanshusharma89** [comment]
I have added About Us screen for the issue: #24

**Comment by rabeehrz** [comment]
@himanshusharma89 Aren't those issues assigned to someone else, why are you adding them in this PR? I don't think it's a good idea to hog on others' issues mate.

**Comment by himanshusharma89** [comment]
@rabeehrz Well someone is getting offended, If this is the case then I'll remove the Bottom Navigation Bar.

**Comment by himanshusharma89** [comment]
@smaranjitghose can you merge this PR and give me the points.

**Pull request closed without merging**
