### PR TITLE
Added a new branch which uses CachedNetworkImage instead of AssetImage in Teams.dart

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closing #274 

Please review and let me know if you want any further changes.

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
Hey, I don't understand what the test which was failed means? Did it fail because I deleted the asset images? It would be great if anyone can guide me

**Comment by smaranjitghose** [comment]
> Hey, I don't understand what the test which was failed means? Did it fail because I deleted the asset images? It would be great if anyone can guide me

It's a bug in the github action

**Review by himanshusharma89 — CHANGES_REQUESTED** [review]
Hey @Saransh-cpp, can you update the .gitignore file from the Blog App and then update it here. We don't need the .idea and .lock in the PR.

**Comment by himanshusharma89** [comment]
Also, can you add a screenshot/gif of the team's page?

**Comment by Saransh-cpp** [comment]
> Hey @Saransh-cpp, can you update the .gitignore file from the Blog App and then update it here. We don't need the .idea and .lock in the PR.

Should I just copy the .gitignore's content from that app and paste it here, then push the changes?

**Comment by himanshusharma89** [comment]
@Saransh-cpp yes. After that you might need to do the following:
git rm -rf --cached .
git add .
After that push the changes and add the screenshot/gif also.

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp yes. After that you might need to do the following:
> git rm -rf --cached .
> git add .
> After that push the changes and add the screenshot/gif also.

git rm -rf --cached shows "No pathspec was given", should I add the path for .lock and .idea, then add .gitignore, commit and push?

also the gif is attached below, the issue with loading screen not showing up in some pictures(icons) has been fixed and I will be pushing that commit too.

ezgif com-gif-maker (1)

**Comment by himanshusharma89** [comment]
@Saransh-cpp you need to do the git rm command before copying the ignore file from Blog App repo. After git rm, paste the update gitignore and then perform add and commit

**Comment by Saransh-cpp** [comment]
@himanshusharma89 still the same error
```
fatal: No pathspec was given. Which files should I remove?
```

**Comment by himanshusharma89** [comment]
> @himanshusharma89 still the same error
> 
> ```
> fatal: No pathspec was given. Which files should I remove?
> ```

Make sure that there is no untracked file.

**Comment by Saransh-cpp** [comment]
I think it worked, please review. Thanks for the guidance @himanshusharma89 .

**Pull request merged**
